{{- if and .Values.externalSecrets.enabled .Values.pickemctl.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "family-pickem.fullname" . }}-pickemctl
  labels:
    {{- include "family-pickem.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "family-pickem.fullname" . }}-pickemctl
    creationPolicy: Owner
  data:
    - secretKey: config.yaml
      remoteRef:
        key: {{ .Values.externalSecrets.pickemctlKey }}
{{- end }}
