{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "family-pickem.fullname" . }}-envvars
  labels:
    {{- include "family-pickem.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "family-pickem.fullname" . }}-envvars
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.envvarsKey }}
{{- end }}
