{{- if and .Values.pickemctl.enabled (not .Values.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "family-pickem.fullname" . }}-pickemctl
  labels:
    {{- include "family-pickem.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- .Values.pickemctl.config | nindent 4 }}
{{- end }}
